### ISSUE TITLE
ubuntu: skip bitcoind compile if already present

### ISSUE THREAD

**Issue by firepol** [Perlover/bitcoin-kit-makefile#2]
Hi there, first of all thanks for this script, it looks really handy and in fact I'm already using it.

Question, I use ubuntu and I added this PPA: https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin
So basically I installed already the latest version of bitcoind.

I'm not very familiar with make... is `i-want-lightning checking` checking if bitcoind already exists, before compiling it? If not, do you think you can add that check? I like the idea to save time and as there is an already compiled and maintained package in the PPA, it would be a good idea to use it.

Thanks for considering this or letting me know. I started compiling and I'm the wait wait wait phase now...

Same for compiling python etc.: I rather install the ubuntu package instead...

**Comment by Perlover** [comment]
Hello!

Thanks for suggestion but bitcoind and lnd here are very bundled together.
For example this script generates the `rpcauth` token for bitcoind config then this token is used in config of LND. Or the LND uses specific TCP ports for `zmqpubraw*` parameters of bitcoind. I don't know how can i separate these parts now.

This script is primarily intended for those who want to set up LND & Bitcoind daemons together without technical configuration.

I can now recommend only this: you can setup default scenario here but when you will do you can manual change the LND configuration to use your bitcoind daemon. But you will need to change config files your bitcoind or this lnd config file. This script uses only local user directory for everything so it's like Docker container but not Docker :) I think are your bitcoind daemon run as other user and other user directory? If yes you can do it without problem after compiling. I will close this issue because i cannot change it. It's very difficult and i have limit resources for this.

And how was your compiling process finished?

**Comment by Perlover** [comment]
> Same for compiling python etc.: I rather install the ubuntu package instead...

I understand but evreything to be installed to ~bitcoin directory (or other your user directory) and it's separated from system. These utilities (python, node.js and so on) to be needed by these compiled software and i don't want to have problems with other version dependencies. I decided to compile maximum to descrease a dependence of utility versions.
